### PR TITLE
Add functionality to read from stdin

### PR DESCRIPTION
**Pull request by casualfred**
I added a '-c' option that will cause the script to read from stdin.

(This is my first github pull request ever!)

### CODE REVIEW

**Comment by dmdmdm** [comment]
Thanks for the update - I am going to accept it.
I think it would be cooler if reading from stdin was automatic.
So the user can just do `pslogscan < myfile`

Piped input can be detected with:

```
if [[ -t 0 ]]; then
    echo stdin is a terminal
else
    echo stdin is a pipe
fi

```

What do you think?

**Comment by casualfred** [comment]
Hi - I like it! I agree that it would be better to detect and read from stdin automatically. I can make the update and do another pull request if you would like me to - whatever you prefer.

**Comment by dmdmdm** [comment]
Sure, go for it

**Comment by dmdmdm** [comment]
I added this to the README...

# Typical Usage with systemd

journalctl -u postfix | pslogscan -c

**Pull request merged**
